// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/comp/Lexer.flex

package comp;
import static comp.Tokens.*;
import java.util.HashMap;
import java.util.Map;
import comp.Tokens;

@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\0\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\10\25\1\24\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\11\1\34\2\35\1\36\1\37\1\40\2\35\1\41"+
    "\2\35\1\42\1\43\1\35\1\44\2\35\1\45\1\46"+
    "\5\35\1\47\1\35\1\50\1\51\1\52\1\0\1\35"+
    "\1\0\1\34\1\53\1\35\1\36\1\37\1\40\2\35"+
    "\1\41\2\35\1\42\1\43\1\35\1\44\2\35\1\45"+
    "\1\46\5\35\1\47\1\35\1\54\1\55\1\56\1\33"+
    "\6\0\1\3\33\0\1\33\35\0\1\33\1\0\1\35"+
    "\7\0\1\35\3\0\1\35\3\0\1\35\1\0\1\35"+
    "\6\0\1\35\1\0\1\35\4\0\1\35\7\0\1\35"+
    "\3\0\1\35\3\0\1\35\1\0\1\35\6\0\1\35"+
    "\1\0\1\35\u012b\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\7\27"+
    "\1\30\1\31\1\32\1\1\1\33\1\34\1\35\1\36"+
    "\2\0\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\27\1\51\1\52\1\40\1\0"+
    "\1\53\1\54\1\55\1\47\1\50\1\56\2\50\1\0"+
    "\1\57\2\56\1\50\2\56\1\0\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\57\0\57"+
    "\0\u011a\0\57\0\57\0\57\0\57\0\57\0\57\0\u0149"+
    "\0\u0178\0\u01a7\0\57\0\57\0\u01d6\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\57\0\57"+
    "\0\57\0\u03ac\0\57\0\57\0\57\0\57\0\u03db\0\u040a"+
    "\0\57\0\u0439\0\u0468\0\u0497\0\u04c6\0\57\0\57\0\57"+
    "\0\u04f5\0\u0524\0\u0553\0\u0263\0\57\0\u0582\0\u05b1\0\u05e0"+
    "\0\u0497\0\u060f\0\u063e\0\u066d\0\u0263\0\u0263\0\u069c\0\u06cb"+
    "\0\57\0\u06fa\0\57\0\57\0\u0729\0\u0758\0\u0787\0\u063e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\3\1\4\1\5\1\6"+
    "\1\2\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\2\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\7\2\30\1\31\1\30\1\32\1\30"+
    "\1\32\1\33\1\30\1\34\1\35\1\36\1\37\1\2"+
    "\1\40\1\30\1\41\1\42\1\43\60\0\1\3\2\0"+
    "\1\3\54\0\1\4\2\0\1\4\102\0\1\44\25\0"+
    "\2\6\1\45\4\6\1\46\41\6\1\47\5\6\2\11"+
    "\1\50\2\11\1\50\5\11\1\51\43\11\24\0\2\20"+
    "\47\0\1\52\4\0\1\53\55\0\1\54\1\0\2\22"+
    "\6\0\14\55\3\0\1\55\34\0\1\56\56\0\1\57"+
    "\56\0\1\60\35\0\4\61\2\0\1\61\2\0\1\61"+
    "\2\0\2\30\6\0\14\30\3\0\1\30\13\0\4\61"+
    "\2\0\1\61\2\0\1\61\2\0\2\30\6\0\10\30"+
    "\1\62\3\30\3\0\1\30\13\0\4\61\2\0\1\61"+
    "\2\0\1\61\2\0\2\30\6\0\1\62\13\30\3\0"+
    "\1\30\13\0\4\61\2\0\1\61\2\0\1\61\2\0"+
    "\2\30\6\0\5\30\1\62\6\30\3\0\1\30\13\0"+
    "\4\61\2\0\1\61\2\0\1\61\2\0\2\30\6\0"+
    "\3\30\1\62\10\30\3\0\1\30\13\0\4\61\2\0"+
    "\1\61\2\0\1\61\2\0\2\30\6\0\5\30\1\62"+
    "\2\30\1\63\3\30\3\0\1\30\13\0\4\61\2\0"+
    "\1\61\2\0\1\61\2\0\2\30\6\0\13\30\1\64"+
    "\3\0\1\30\60\0\1\65\1\0\2\6\4\0\51\6"+
    "\13\50\1\51\43\50\16\66\1\67\40\66\2\53\1\0"+
    "\2\53\1\0\51\53\22\0\1\70\1\0\2\71\55\0"+
    "\2\72\6\0\14\55\3\0\1\55\13\0\4\61\2\0"+
    "\1\61\2\0\1\61\12\0\14\73\3\0\1\73\13\0"+
    "\1\74\3\61\2\0\1\61\2\0\1\61\2\0\1\75"+
    "\1\76\6\0\14\30\3\0\1\77\13\0\4\61\2\0"+
    "\1\61\2\0\1\61\2\0\2\30\6\0\6\30\1\62"+
    "\5\30\3\0\1\30\3\0\16\66\1\100\40\66\16\0"+
    "\1\67\4\0\1\101\55\0\1\70\1\0\2\70\55\0"+
    "\2\72\6\0\14\72\3\0\1\72\27\0\2\73\6\0"+
    "\14\73\3\0\1\73\13\0\1\102\3\61\2\0\1\61"+
    "\2\0\1\61\2\0\1\103\1\104\6\0\14\73\3\0"+
    "\1\105\13\0\1\102\3\61\2\0\1\61\2\0\1\61"+
    "\2\0\1\75\1\76\6\0\14\30\3\0\1\106\3\0"+
    "\16\107\1\100\4\107\1\101\33\107\10\0\4\61\2\0"+
    "\1\61\2\0\1\61\3\0\1\103\6\0\14\73\3\0"+
    "\1\73\27\0\1\73\1\110\6\0\14\73\3\0\1\73"+
    "\13\0\4\61\2\0\1\61\2\0\1\61\2\0\1\30"+
    "\1\75\6\0\14\30\3\0\1\30\3\0\16\107\1\100"+
    "\40\107";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1974];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\2\11\1\1\6\11\3\1\2\11"+
    "\12\1\3\11\1\1\4\11\2\0\1\11\4\1\3\11"+
    "\4\1\1\11\1\1\1\0\10\1\1\0\1\11\1\1"+
    "\2\11\2\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Map<String, Tokens> keywords;

    public void initKeywords() {
        keywords = new HashMap<>();
        // Palabras reservadas (agrega/quita según necesites; clave en minúsculas)
        keywords.put("nota", KW_NOTA);
        keywords.put("acorde", KW_ACORDE);
        keywords.put("melodia", KW_MELODIA);
        keywords.put("tiempo", KW_TIEMPO);
        keywords.put("octava", KW_OCTAVA);
        keywords.put("tocar", KW_TOCAR);
        keywords.put("silencio", KW_SILENCIO);
        keywords.put("compas", KW_COMPAS);
        keywords.put("tempo", KW_TEMPO);
        keywords.put("tono", KW_TONO);
        keywords.put("escala", KW_ESCALA);

        keywords.put("lista", KW_LISTA);
        keywords.put("secuencia", KW_SECUENCIA);
        keywords.put("definir", KW_DEFINIR);

        // Estructuras de control
        keywords.put("si_", KW_SI);        // Estructura condicional
        keywords.put("sino", KW_SINO);
        keywords.put("segun", KW_SEGUN);
        keywords.put("caso", KW_CASO);
        keywords.put("defecto", KW_DEFECTO);
        keywords.put("repetir", KW_REPETIR);
        keywords.put("veces", KW_VECES);    // NUEVO: para "repetir X veces"
        keywords.put("mientras", KW_MIENTRAS);
        keywords.put("romper", KW_ROMPER);
        keywords.put("continuar", KW_CONTINUAR);

        keywords.put("seccion", KW_SECCION);
        keywords.put("fin", KW_FIN);
        keywords.put("mostrar", KW_MOSTRAR);
        keywords.put("leer", KW_LEER);

        // Valores para "tono" - NUEVOS
        keywords.put("mayor", KW_MAYOR);
        keywords.put("menor", KW_MENOR);

        //valores constantes
        keywords.put("adagio", KW_ADAGIO);   // Nuevo
        keywords.put("andante", KW_ANDANTE); // Nuevo
        keywords.put("allegro", KW_ALLEGRO); // Nuevo

        // Valores booleanos - NUEVOS
        keywords.put("true", KW_TRUE);     // ← AÑADIDO
        keywords.put("false", KW_FALSE);   // ← AÑADIDO

        // Notas musicales - "si" no se incluye aquí para evitar conflictos
        keywords.put("do", KW_DO);
        keywords.put("re", KW_RE);
        keywords.put("mi", KW_MI);
        keywords.put("fa", KW_FA);
        keywords.put("sol", KW_SOL);
        keywords.put("la", KW_LA);
        // "si" se maneja exclusivamente en el patrón NOTE
    }

    public String lexeme;
    public Tokens type;
    public int line;
    public int column;
    public TokenAlmacen token;

    // Helper para mapear identificadores a keywords
    private Tokens lookupKeyword(String text) {
        if (keywords == null) initKeywords();
        Tokens t = keywords.get(text.toLowerCase());
        return t;
    }
    
    // Método para verificar si una nota está delimitada correctamente
    private boolean esNotaDelimitada() {
        // Verificar caracter anterior
        int start = zzStartRead;
        if (start > 0) {
            char anterior = zzBuffer[start - 1];
            if (Character.isLetterOrDigit(anterior) || anterior == '_') {
                return false;
            }
        }
        
        // Verificar caracter posterior
        int end = start + yylength();
        if (end < zzEndRead) {
            char siguiente = zzBuffer[end];
            if (Character.isLetterOrDigit(siguiente) || siguiente == '_') {
                return false;
            }
        }
        
        return true;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public TokenAlmacen nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return new TokenAlmacen(Tokens.EOF, "EOF", yyline + 1, yycolumn + 1);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "'", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 48: break;
          case 2:
            { /* ignore whitespace */
            }
          // fall through
          case 49: break;
          case 3:
            { /* increment line is automatic with %line; ignore */
            }
          // fall through
          case 50: break;
          case 4:
            { lexeme = yytext(); type = opNot; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 51: break;
          case 5:
            { return new TokenAlmacen(ERROR, "Cadena sin cerrar al final del archivo: " + yytext(), yyline + 1, yycolumn + 1);
            }
          // fall through
          case 52: break;
          case 6:
            { return new TokenAlmacen(ERROR, "Carácter no reconocido: '" + yytext() + "'", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 53: break;
          case 7:
            { lexeme = yytext(); type = Modulo; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 54: break;
          case 8:
            { return new TokenAlmacen(ERROR, "Comentario con & sin cerrar: " + yytext(), yyline + 1, yycolumn + 1);
            }
          // fall through
          case 55: break;
          case 9:
            { lexeme = yytext();
    type = ParenAper;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 56: break;
          case 10:
            { lexeme = yytext();
    type = ParenCierre;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 57: break;
          case 11:
            { lexeme = yytext(); type = Multiplicacion; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 58: break;
          case 12:
            { lexeme = yytext(); type = Suma; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 59: break;
          case 13:
            { lexeme = yytext();
    type = Coma;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 60: break;
          case 14:
            { lexeme = yytext(); type = Resta; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 61: break;
          case 15:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "' (sin parte entera)", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 62: break;
          case 16:
            { lexeme = yytext(); type = Division; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 63: break;
          case 17:
            { lexeme = yytext();
    type = Numero;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 64: break;
          case 18:
            { lexeme = yytext();
    type = DosPuntos;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 65: break;
          case 19:
            { lexeme = yytext();
    type = PuntoComa;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 66: break;
          case 20:
            { lexeme = yytext(); type = opRel_men; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 67: break;
          case 21:
            { lexeme = yytext();
    type = Igual;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 68: break;
          case 22:
            { lexeme = yytext(); type = opRel_may; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 69: break;
          case 23:
            { lexeme = yytext();
    Tokens k = lookupKeyword(lexeme);
    if (k != null) {
        type = k;
    } else {
        type = Identificador; /* token por defecto para identificadores */
    }
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 70: break;
          case 24:
            { lexeme = yytext();
    type = CorcheteAper;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 71: break;
          case 25:
            { lexeme = yytext();
    type = CorcheteCierre;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 72: break;
          case 26:
            { lexeme = yytext();
    type = LlaveAper;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 73: break;
          case 27:
            { lexeme = yytext();
    type = LlaveCierre;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 74: break;
          case 28:
            { lexeme = yytext(); type = opRel_dif; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 75: break;
          case 29:
            { return new TokenAlmacen(ERROR, "Cadena sin cerrar: " + yytext(), yyline + 1, yycolumn + 1);
            }
          // fall through
          case 76: break;
          case 30:
            { lexeme = yytext();
    type = CADENA;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 77: break;
          case 31:
            { /* ignore comentarios entre & */
            }
          // fall through
          case 78: break;
          case 32:
            { return new TokenAlmacen(ERROR, "Comentario de bloque sin cerrar: " + yytext(), yyline + 1, yycolumn + 1);
            }
          // fall through
          case 79: break;
          case 33:
            { /* ignore line comments */
            }
          // fall through
          case 80: break;
          case 34:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "' (termina con punto decimal)", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 81: break;
          case 35:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "' (mezcla números con letras)", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 82: break;
          case 36:
            { lexeme = yytext(); type = opRel_menIgual; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 83: break;
          case 37:
            { lexeme = yytext(); type = opRel_ig; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 84: break;
          case 38:
            { lexeme = yytext(); type = opRel_mayIgual; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 85: break;
          case 39:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "' (caracteres inválidos en identificador)", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 86: break;
          case 40:
            { String text = yytext();
    // Verificar que la nota esté delimitada correctamente
    if (esNotaDelimitada()) {
        // Verificar que tenga formato válido de nota
        if (text.matches("(?i)^(do|re|mi|fa|sol|la|si)([#b]?[1-8]?)$")) {
            return new TokenAlmacen(Tokens.NOTE, text, yyline + 1, yycolumn + 1);
        }
    }
    // Si no es una nota válida, no hacer nada (dejar que continúe)
            }
          // fall through
          case 87: break;
          case 41:
            { lexeme = yytext(); type = opAnd; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 88: break;
          case 42:
            { lexeme = yytext(); type = opOr; line = yyline + 1; column = yycolumn + 1; token = new TokenAlmacen(type,lexeme,line,column); return token;
            }
          // fall through
          case 89: break;
          case 43:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "' (múltiples puntos decimales)", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 90: break;
          case 44:
            { lexeme = yytext();
    type = NumeroDecimal;
    line = yyline + 1;
    column = yycolumn + 1;
    token = new TokenAlmacen(type,lexeme,line,column);
    return token;
            }
          // fall through
          case 91: break;
          case 45:
            { return new TokenAlmacen(ERROR, "Cadena inválida: '" + yytext() + "' (identificador que empieza con número)", yyline + 1, yycolumn + 1);
            }
          // fall through
          case 92: break;
          case 46:
            { String text = yytext();
    // Verificar que sea realmente una nota delimitada (no parte de una palabra)
    if (esNotaDelimitada()) {
        if (text.matches("(?i).*(##|bb|#b|b#).*")) {
            return new TokenAlmacen(ERROR, "Nota con alteraciones múltiples inválidas: " + text, yyline + 1, yycolumn + 1);
        } else {
            return new TokenAlmacen(ERROR, "Nota con octava inválida (debe ser 1-8): " + text, yyline + 1, yycolumn + 1);
        }
    }
    // Si no es una nota delimitada, continuar sin hacer nada
            }
          // fall through
          case 93: break;
          case 47:
            { /* ignore block comments */
            }
          // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
