
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package comp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KW_SECCION = 31;
  public static final int KW_DEFECTO = 40;
  public static final int KW_FALSE = 65;
  public static final int PuntoComa = 9;
  public static final int Coma = 8;
  public static final int opRel_men = 29;
  public static final int KW_MELODIA = 50;
  public static final int opNot = 24;
  public static final int CorcheteCierre = 16;
  public static final int opAnd = 22;
  public static final int KW_TONO = 57;
  public static final int KW_ALLEGRO = 63;
  public static final int KW_CASO = 39;
  public static final int KW_FIN = 32;
  public static final int opRel_menIgual = 27;
  public static final int KW_COMPAS = 55;
  public static final int KW_ACORDE = 49;
  public static final int KW_MOSTRAR = 33;
  public static final int opRel_may = 30;
  public static final int LlaveCierre = 12;
  public static final int KW_SI = 36;
  public static final int KW_ANDANTE = 62;
  public static final int KW_ESCALA = 58;
  public static final int KW_SINO = 37;
  public static final int Division = 20;
  public static final int NumeroDecimal = 6;
  public static final int Modulo = 21;
  public static final int EOF = 0;
  public static final int DosPuntos = 10;
  public static final int ParenAper = 13;
  public static final int KW_CONTINUAR = 45;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int KW_LISTA = 52;
  public static final int KW_TEMPO = 56;
  public static final int CorcheteAper = 15;
  public static final int KW_TRUE = 64;
  public static final int opOr = 23;
  public static final int KW_OCTAVA = 54;
  public static final int opRel_ig = 25;
  public static final int KW_ROMPER = 44;
  public static final int KW_MIENTRAS = 43;
  public static final int ParenCierre = 14;
  public static final int KW_MENOR = 60;
  public static final int KW_ADAGIO = 61;
  public static final int KW_TOCAR = 46;
  public static final int NOTE = 3;
  public static final int KW_VECES = 42;
  public static final int KW_MAYOR = 59;
  public static final int Identificador = 4;
  public static final int KW_SECUENCIA = 51;
  public static final int KW_TIEMPO = 53;
  public static final int Resta = 18;
  public static final int opRel_mayIgual = 28;
  public static final int KW_NOTA = 48;
  public static final int KW_REPETIR = 41;
  public static final int Multiplicacion = 19;
  public static final int LlaveAper = 11;
  public static final int KW_SILENCIO = 47;
  public static final int opRel_dif = 26;
  public static final int Numero = 5;
  public static final int KW_LEER = 34;
  public static final int Suma = 17;
  public static final int KW_SEGUN = 38;
  public static final int KW_DEFINIR = 35;
  public static final int Igual = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "NOTE",
  "Identificador",
  "Numero",
  "NumeroDecimal",
  "Igual",
  "Coma",
  "PuntoComa",
  "DosPuntos",
  "LlaveAper",
  "LlaveCierre",
  "ParenAper",
  "ParenCierre",
  "CorcheteAper",
  "CorcheteCierre",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Modulo",
  "opAnd",
  "opOr",
  "opNot",
  "opRel_ig",
  "opRel_dif",
  "opRel_menIgual",
  "opRel_mayIgual",
  "opRel_men",
  "opRel_may",
  "KW_SECCION",
  "KW_FIN",
  "KW_MOSTRAR",
  "KW_LEER",
  "KW_DEFINIR",
  "KW_SI",
  "KW_SINO",
  "KW_SEGUN",
  "KW_CASO",
  "KW_DEFECTO",
  "KW_REPETIR",
  "KW_VECES",
  "KW_MIENTRAS",
  "KW_ROMPER",
  "KW_CONTINUAR",
  "KW_TOCAR",
  "KW_SILENCIO",
  "KW_NOTA",
  "KW_ACORDE",
  "KW_MELODIA",
  "KW_SECUENCIA",
  "KW_LISTA",
  "KW_TIEMPO",
  "KW_OCTAVA",
  "KW_COMPAS",
  "KW_TEMPO",
  "KW_TONO",
  "KW_ESCALA",
  "KW_MAYOR",
  "KW_MENOR",
  "KW_ADAGIO",
  "KW_ANDANTE",
  "KW_ALLEGRO",
  "KW_TRUE",
  "KW_FALSE"
  };
}

